### ISSUE TITLE
"fatal error: lv2.h" when compile in Debian 11

### ISSUE THREAD

**Issue by midiaudio** [moddevices/mod-utilities#10]
Hi,

I try to compile all plugins in Debian 11. When I type `make` I have the next output for all plugins (here one example):

```
src/LowPassFilter.cpp:5:10: fatal error: lv2.h: No file or folder
```

**Comment by falkTX** [comment]
lv2-dev is installed?

**Comment by midiaudio** [comment]
Thanks @falkTX for the hint. A missing dependency.

`sudo apt install lv2-dev`
