### ISSUE TITLE
graphical issues in switchbox3

### ISSUE THREAD

**Issue by falkTX** [moddevices/mod-utilities#2]
You can see it in the screenshot here https://raw.githubusercontent.com/portalmod/mod-utilities/a363f5f3a33a2a584653d5d2b3e045d7b5dbe565/SwitchBox3/ttl/modgui/SwitchBox2.png

When used in mod-ui/client this can be seen as well:

![snapshot15](https://cloud.githubusercontent.com/assets/1334853/5137640/37d80aae-7135-11e4-9343-7d6b177dba75.png)

**Comment by aspiers** [comment]
AFAICS SwitchBox3 no longer exists, so presumably this can be closed?  However see https://forum.moddevices.com/t/n-way-switchbox/1386 which requests that it does exist :-)  I also found [this old code for it](https://github.com/moddevices/mod-utilities/blob/a363f5f3a33a2a584653d5d2b3e045d7b5dbe565/SwitchBox3/src/switchbox3.cpp) in the git history...

**Comment by falkTX** [comment]
both the UI and the code for it were completely broken, so it got removed and deleted.
I forgot to close this issue before.
